#!/usr/bin/env python3
import rospy
import actionlib
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal

def movebase_client():

    client = actionlib.SimpleActionClient('move_base1',MoveBaseAction)
    client.wait_for_server()

    goal = MoveBaseGoal()
    goal.target_pose.header.frame_id = "map"
    goal.target_pose.header.stamp = rospy.Time.now()
    print("Inserire coordinata X nel formato n.n: ")
    goal.target_pose.pose.position.x = input()
    print("Inserire coordinata y nel formato n.n: ")
    goal.target_pose.pose.position.y = input()
    print("Inserire coordinata z nel formato n.n: ")
    goal.target_pose.pose.orientation.z = input()
    print("Inserire coordinata w nel formato n.n: ")
    goal.target_pose.pose.orientation.w = input()

    client.send_goal(goal)
    wait = client.wait_for_result()
    if not wait:
        rospy.logerr("Action server not available!")
        rospy.signal_shutdown("Action server not available!")
    else:
        return client.get_result()

if __name__ == '__main__':
    try:
        rospy.init_node('movebase_client_py')
        result = movebase_client()
        if result:
            rospy.loginfo("Goal execution done!")
    except rospy.ROSInterruptException:
        rospy.loginfo("Navigation test finished.")